//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCV.ServiceOCV {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrayInfoOCV", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TrayInfoOCV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trayCodeField;
        
        private int oprationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oprationVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCV.ServiceOCV.TrayInfoResult[] TrayInfoLstResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCV.ServiceOCV.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EquipNum {
            get {
                return this.EquipNumField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipNumField, value) != true)) {
                    this.EquipNumField = value;
                    this.RaisePropertyChanged("EquipNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string trayCode {
            get {
                return this.trayCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.trayCodeField, value) != true)) {
                    this.trayCodeField = value;
                    this.RaisePropertyChanged("trayCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int oprationType {
            get {
                return this.oprationTypeField;
            }
            set {
                if ((this.oprationTypeField.Equals(value) != true)) {
                    this.oprationTypeField = value;
                    this.RaisePropertyChanged("oprationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string oprationVersion {
            get {
                return this.oprationVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.oprationVersionField, value) != true)) {
                    this.oprationVersionField = value;
                    this.RaisePropertyChanged("oprationVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public OCV.ServiceOCV.TrayInfoResult[] TrayInfoLstResult {
            get {
                return this.TrayInfoLstResultField;
            }
            set {
                if ((object.ReferenceEquals(this.TrayInfoLstResultField, value) != true)) {
                    this.TrayInfoLstResultField = value;
                    this.RaisePropertyChanged("TrayInfoLstResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public OCV.ServiceOCV.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrayInfoResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TrayInfoResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatteryCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BatteryCode {
            get {
                return this.BatteryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BatteryCodeField, value) != true)) {
                    this.BatteryCodeField = value;
                    this.RaisePropertyChanged("BatteryCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatteryInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BatteryInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatteryCodeField;
        
        private int ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BatteryCode {
            get {
                return this.BatteryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BatteryCodeField, value) != true)) {
                    this.BatteryCodeField = value;
                    this.RaisePropertyChanged("BatteryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOCV.OCVWebServiceSoap")]
    public interface OCVWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ConnectTestResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConnectTest", ReplyAction="*")]
        OCV.ServiceOCV.ConnectTestResponse ConnectTest(OCV.ServiceOCV.ConnectTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConnectTest", ReplyAction="*")]
        System.Threading.Tasks.Task<OCV.ServiceOCV.ConnectTestResponse> ConnectTestAsync(OCV.ServiceOCV.ConnectTestRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 EquipNum 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOCVStatus", ReplyAction="*")]
        OCV.ServiceOCV.UpdateOCVStatusResponse UpdateOCVStatus(OCV.ServiceOCV.UpdateOCVStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOCVStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<OCV.ServiceOCV.UpdateOCVStatusResponse> UpdateOCVStatusAsync(OCV.ServiceOCV.UpdateOCVStatusRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 EquipNum 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTechnologyInfoByBarCode", ReplyAction="*")]
        OCV.ServiceOCV.getTechnologyInfoByBarCodeResponse getTechnologyInfoByBarCode(OCV.ServiceOCV.getTechnologyInfoByBarCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTechnologyInfoByBarCode", ReplyAction="*")]
        System.Threading.Tasks.Task<OCV.ServiceOCV.getTechnologyInfoByBarCodeResponse> getTechnologyInfoByBarCodeAsync(OCV.ServiceOCV.getTechnologyInfoByBarCodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 EquipNum 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOCVTestResultByBarCode", ReplyAction="*")]
        OCV.ServiceOCV.getOCVTestResultByBarCodeResponse getOCVTestResultByBarCode(OCV.ServiceOCV.getOCVTestResultByBarCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOCVTestResultByBarCode", ReplyAction="*")]
        System.Threading.Tasks.Task<OCV.ServiceOCV.getOCVTestResultByBarCodeResponse> getOCVTestResultByBarCodeAsync(OCV.ServiceOCV.getOCVTestResultByBarCodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 EquipNum 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestOutFeed", ReplyAction="*")]
        OCV.ServiceOCV.RequestOutFeedResponse RequestOutFeed(OCV.ServiceOCV.RequestOutFeedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestOutFeed", ReplyAction="*")]
        System.Threading.Tasks.Task<OCV.ServiceOCV.RequestOutFeedResponse> RequestOutFeedAsync(OCV.ServiceOCV.RequestOutFeedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConnectTest", Namespace="http://tempuri.org/", Order=0)]
        public OCV.ServiceOCV.ConnectTestRequestBody Body;
        
        public ConnectTestRequest() {
        }
        
        public ConnectTestRequest(OCV.ServiceOCV.ConnectTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConnectTestRequestBody {
        
        public ConnectTestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConnectTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public OCV.ServiceOCV.ConnectTestResponseBody Body;
        
        public ConnectTestResponse() {
        }
        
        public ConnectTestResponse(OCV.ServiceOCV.ConnectTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConnectTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConnectTestResult;
        
        public ConnectTestResponseBody() {
        }
        
        public ConnectTestResponseBody(string ConnectTestResult) {
            this.ConnectTestResult = ConnectTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOCVStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOCVStatus", Namespace="http://tempuri.org/", Order=0)]
        public OCV.ServiceOCV.UpdateOCVStatusRequestBody Body;
        
        public UpdateOCVStatusRequest() {
        }
        
        public UpdateOCVStatusRequest(OCV.ServiceOCV.UpdateOCVStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOCVStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EquipNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int WorkMode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorMsg;
        
        public UpdateOCVStatusRequestBody() {
        }
        
        public UpdateOCVStatusRequestBody(string EquipNum, int WorkMode, int Status, string ErrorMsg) {
            this.EquipNum = EquipNum;
            this.WorkMode = WorkMode;
            this.Status = Status;
            this.ErrorMsg = ErrorMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOCVStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOCVStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public OCV.ServiceOCV.UpdateOCVStatusResponseBody Body;
        
        public UpdateOCVStatusResponse() {
        }
        
        public UpdateOCVStatusResponse(OCV.ServiceOCV.UpdateOCVStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOCVStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OCV.ServiceOCV.Result UpdateOCVStatusResult;
        
        public UpdateOCVStatusResponseBody() {
        }
        
        public UpdateOCVStatusResponseBody(OCV.ServiceOCV.Result UpdateOCVStatusResult) {
            this.UpdateOCVStatusResult = UpdateOCVStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTechnologyInfoByBarCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTechnologyInfoByBarCode", Namespace="http://tempuri.org/", Order=0)]
        public OCV.ServiceOCV.getTechnologyInfoByBarCodeRequestBody Body;
        
        public getTechnologyInfoByBarCodeRequest() {
        }
        
        public getTechnologyInfoByBarCodeRequest(OCV.ServiceOCV.getTechnologyInfoByBarCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTechnologyInfoByBarCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EquipNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BarCode;
        
        public getTechnologyInfoByBarCodeRequestBody() {
        }
        
        public getTechnologyInfoByBarCodeRequestBody(string EquipNum, string BarCode) {
            this.EquipNum = EquipNum;
            this.BarCode = BarCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTechnologyInfoByBarCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTechnologyInfoByBarCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public OCV.ServiceOCV.getTechnologyInfoByBarCodeResponseBody Body;
        
        public getTechnologyInfoByBarCodeResponse() {
        }
        
        public getTechnologyInfoByBarCodeResponse(OCV.ServiceOCV.getTechnologyInfoByBarCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTechnologyInfoByBarCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OCV.ServiceOCV.TrayInfoOCV getTechnologyInfoByBarCodeResult;
        
        public getTechnologyInfoByBarCodeResponseBody() {
        }
        
        public getTechnologyInfoByBarCodeResponseBody(OCV.ServiceOCV.TrayInfoOCV getTechnologyInfoByBarCodeResult) {
            this.getTechnologyInfoByBarCodeResult = getTechnologyInfoByBarCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOCVTestResultByBarCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOCVTestResultByBarCode", Namespace="http://tempuri.org/", Order=0)]
        public OCV.ServiceOCV.getOCVTestResultByBarCodeRequestBody Body;
        
        public getOCVTestResultByBarCodeRequest() {
        }
        
        public getOCVTestResultByBarCodeRequest(OCV.ServiceOCV.getOCVTestResultByBarCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getOCVTestResultByBarCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EquipNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BarCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public OCV.ServiceOCV.BatteryInfo[] lstBattery;
        
        public getOCVTestResultByBarCodeRequestBody() {
        }
        
        public getOCVTestResultByBarCodeRequestBody(string EquipNum, string BarCode, OCV.ServiceOCV.BatteryInfo[] lstBattery) {
            this.EquipNum = EquipNum;
            this.BarCode = BarCode;
            this.lstBattery = lstBattery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOCVTestResultByBarCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOCVTestResultByBarCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public OCV.ServiceOCV.getOCVTestResultByBarCodeResponseBody Body;
        
        public getOCVTestResultByBarCodeResponse() {
        }
        
        public getOCVTestResultByBarCodeResponse(OCV.ServiceOCV.getOCVTestResultByBarCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getOCVTestResultByBarCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OCV.ServiceOCV.Result getOCVTestResultByBarCodeResult;
        
        public getOCVTestResultByBarCodeResponseBody() {
        }
        
        public getOCVTestResultByBarCodeResponseBody(OCV.ServiceOCV.Result getOCVTestResultByBarCodeResult) {
            this.getOCVTestResultByBarCodeResult = getOCVTestResultByBarCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOutFeedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOutFeed", Namespace="http://tempuri.org/", Order=0)]
        public OCV.ServiceOCV.RequestOutFeedRequestBody Body;
        
        public RequestOutFeedRequest() {
        }
        
        public RequestOutFeedRequest(OCV.ServiceOCV.RequestOutFeedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestOutFeedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EquipNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BarCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Status;
        
        public RequestOutFeedRequestBody() {
        }
        
        public RequestOutFeedRequestBody(string EquipNum, string BarCode, string Status) {
            this.EquipNum = EquipNum;
            this.BarCode = BarCode;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOutFeedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOutFeedResponse", Namespace="http://tempuri.org/", Order=0)]
        public OCV.ServiceOCV.RequestOutFeedResponseBody Body;
        
        public RequestOutFeedResponse() {
        }
        
        public RequestOutFeedResponse(OCV.ServiceOCV.RequestOutFeedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestOutFeedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OCV.ServiceOCV.Result RequestOutFeedResult;
        
        public RequestOutFeedResponseBody() {
        }
        
        public RequestOutFeedResponseBody(OCV.ServiceOCV.Result RequestOutFeedResult) {
            this.RequestOutFeedResult = RequestOutFeedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OCVWebServiceSoapChannel : OCV.ServiceOCV.OCVWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OCVWebServiceSoapClient : System.ServiceModel.ClientBase<OCV.ServiceOCV.OCVWebServiceSoap>, OCV.ServiceOCV.OCVWebServiceSoap {
        
        public OCVWebServiceSoapClient() {
        }
        
        public OCVWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OCVWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OCVWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OCVWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OCV.ServiceOCV.ConnectTestResponse OCV.ServiceOCV.OCVWebServiceSoap.ConnectTest(OCV.ServiceOCV.ConnectTestRequest request) {
            return base.Channel.ConnectTest(request);
        }
        
        public string ConnectTest() {
            OCV.ServiceOCV.ConnectTestRequest inValue = new OCV.ServiceOCV.ConnectTestRequest();
            inValue.Body = new OCV.ServiceOCV.ConnectTestRequestBody();
            OCV.ServiceOCV.ConnectTestResponse retVal = ((OCV.ServiceOCV.OCVWebServiceSoap)(this)).ConnectTest(inValue);
            return retVal.Body.ConnectTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OCV.ServiceOCV.ConnectTestResponse> OCV.ServiceOCV.OCVWebServiceSoap.ConnectTestAsync(OCV.ServiceOCV.ConnectTestRequest request) {
            return base.Channel.ConnectTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OCV.ServiceOCV.ConnectTestResponse> ConnectTestAsync() {
            OCV.ServiceOCV.ConnectTestRequest inValue = new OCV.ServiceOCV.ConnectTestRequest();
            inValue.Body = new OCV.ServiceOCV.ConnectTestRequestBody();
            return ((OCV.ServiceOCV.OCVWebServiceSoap)(this)).ConnectTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OCV.ServiceOCV.UpdateOCVStatusResponse OCV.ServiceOCV.OCVWebServiceSoap.UpdateOCVStatus(OCV.ServiceOCV.UpdateOCVStatusRequest request) {
            return base.Channel.UpdateOCVStatus(request);
        }
        
        public OCV.ServiceOCV.Result UpdateOCVStatus(string EquipNum, int WorkMode, int Status, string ErrorMsg) {
            OCV.ServiceOCV.UpdateOCVStatusRequest inValue = new OCV.ServiceOCV.UpdateOCVStatusRequest();
            inValue.Body = new OCV.ServiceOCV.UpdateOCVStatusRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.WorkMode = WorkMode;
            inValue.Body.Status = Status;
            inValue.Body.ErrorMsg = ErrorMsg;
            OCV.ServiceOCV.UpdateOCVStatusResponse retVal = ((OCV.ServiceOCV.OCVWebServiceSoap)(this)).UpdateOCVStatus(inValue);
            return retVal.Body.UpdateOCVStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OCV.ServiceOCV.UpdateOCVStatusResponse> OCV.ServiceOCV.OCVWebServiceSoap.UpdateOCVStatusAsync(OCV.ServiceOCV.UpdateOCVStatusRequest request) {
            return base.Channel.UpdateOCVStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<OCV.ServiceOCV.UpdateOCVStatusResponse> UpdateOCVStatusAsync(string EquipNum, int WorkMode, int Status, string ErrorMsg) {
            OCV.ServiceOCV.UpdateOCVStatusRequest inValue = new OCV.ServiceOCV.UpdateOCVStatusRequest();
            inValue.Body = new OCV.ServiceOCV.UpdateOCVStatusRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.WorkMode = WorkMode;
            inValue.Body.Status = Status;
            inValue.Body.ErrorMsg = ErrorMsg;
            return ((OCV.ServiceOCV.OCVWebServiceSoap)(this)).UpdateOCVStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OCV.ServiceOCV.getTechnologyInfoByBarCodeResponse OCV.ServiceOCV.OCVWebServiceSoap.getTechnologyInfoByBarCode(OCV.ServiceOCV.getTechnologyInfoByBarCodeRequest request) {
            return base.Channel.getTechnologyInfoByBarCode(request);
        }
        
        public OCV.ServiceOCV.TrayInfoOCV getTechnologyInfoByBarCode(string EquipNum, string BarCode) {
            OCV.ServiceOCV.getTechnologyInfoByBarCodeRequest inValue = new OCV.ServiceOCV.getTechnologyInfoByBarCodeRequest();
            inValue.Body = new OCV.ServiceOCV.getTechnologyInfoByBarCodeRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.BarCode = BarCode;
            OCV.ServiceOCV.getTechnologyInfoByBarCodeResponse retVal = ((OCV.ServiceOCV.OCVWebServiceSoap)(this)).getTechnologyInfoByBarCode(inValue);
            return retVal.Body.getTechnologyInfoByBarCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OCV.ServiceOCV.getTechnologyInfoByBarCodeResponse> OCV.ServiceOCV.OCVWebServiceSoap.getTechnologyInfoByBarCodeAsync(OCV.ServiceOCV.getTechnologyInfoByBarCodeRequest request) {
            return base.Channel.getTechnologyInfoByBarCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OCV.ServiceOCV.getTechnologyInfoByBarCodeResponse> getTechnologyInfoByBarCodeAsync(string EquipNum, string BarCode) {
            OCV.ServiceOCV.getTechnologyInfoByBarCodeRequest inValue = new OCV.ServiceOCV.getTechnologyInfoByBarCodeRequest();
            inValue.Body = new OCV.ServiceOCV.getTechnologyInfoByBarCodeRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.BarCode = BarCode;
            return ((OCV.ServiceOCV.OCVWebServiceSoap)(this)).getTechnologyInfoByBarCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OCV.ServiceOCV.getOCVTestResultByBarCodeResponse OCV.ServiceOCV.OCVWebServiceSoap.getOCVTestResultByBarCode(OCV.ServiceOCV.getOCVTestResultByBarCodeRequest request) {
            return base.Channel.getOCVTestResultByBarCode(request);
        }
        
        public OCV.ServiceOCV.Result getOCVTestResultByBarCode(string EquipNum, string BarCode, OCV.ServiceOCV.BatteryInfo[] lstBattery) {
            OCV.ServiceOCV.getOCVTestResultByBarCodeRequest inValue = new OCV.ServiceOCV.getOCVTestResultByBarCodeRequest();
            inValue.Body = new OCV.ServiceOCV.getOCVTestResultByBarCodeRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.BarCode = BarCode;
            inValue.Body.lstBattery = lstBattery;
            OCV.ServiceOCV.getOCVTestResultByBarCodeResponse retVal = ((OCV.ServiceOCV.OCVWebServiceSoap)(this)).getOCVTestResultByBarCode(inValue);
            return retVal.Body.getOCVTestResultByBarCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OCV.ServiceOCV.getOCVTestResultByBarCodeResponse> OCV.ServiceOCV.OCVWebServiceSoap.getOCVTestResultByBarCodeAsync(OCV.ServiceOCV.getOCVTestResultByBarCodeRequest request) {
            return base.Channel.getOCVTestResultByBarCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OCV.ServiceOCV.getOCVTestResultByBarCodeResponse> getOCVTestResultByBarCodeAsync(string EquipNum, string BarCode, OCV.ServiceOCV.BatteryInfo[] lstBattery) {
            OCV.ServiceOCV.getOCVTestResultByBarCodeRequest inValue = new OCV.ServiceOCV.getOCVTestResultByBarCodeRequest();
            inValue.Body = new OCV.ServiceOCV.getOCVTestResultByBarCodeRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.BarCode = BarCode;
            inValue.Body.lstBattery = lstBattery;
            return ((OCV.ServiceOCV.OCVWebServiceSoap)(this)).getOCVTestResultByBarCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OCV.ServiceOCV.RequestOutFeedResponse OCV.ServiceOCV.OCVWebServiceSoap.RequestOutFeed(OCV.ServiceOCV.RequestOutFeedRequest request) {
            return base.Channel.RequestOutFeed(request);
        }
        
        public OCV.ServiceOCV.Result RequestOutFeed(string EquipNum, string BarCode, string Status) {
            OCV.ServiceOCV.RequestOutFeedRequest inValue = new OCV.ServiceOCV.RequestOutFeedRequest();
            inValue.Body = new OCV.ServiceOCV.RequestOutFeedRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.BarCode = BarCode;
            inValue.Body.Status = Status;
            OCV.ServiceOCV.RequestOutFeedResponse retVal = ((OCV.ServiceOCV.OCVWebServiceSoap)(this)).RequestOutFeed(inValue);
            return retVal.Body.RequestOutFeedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OCV.ServiceOCV.RequestOutFeedResponse> OCV.ServiceOCV.OCVWebServiceSoap.RequestOutFeedAsync(OCV.ServiceOCV.RequestOutFeedRequest request) {
            return base.Channel.RequestOutFeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<OCV.ServiceOCV.RequestOutFeedResponse> RequestOutFeedAsync(string EquipNum, string BarCode, string Status) {
            OCV.ServiceOCV.RequestOutFeedRequest inValue = new OCV.ServiceOCV.RequestOutFeedRequest();
            inValue.Body = new OCV.ServiceOCV.RequestOutFeedRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.BarCode = BarCode;
            inValue.Body.Status = Status;
            return ((OCV.ServiceOCV.OCVWebServiceSoap)(this)).RequestOutFeedAsync(inValue);
        }
    }
}
