//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace OCV.YL_WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="indexSoap", Namespace="http://kinte.com/")]
    public partial class index : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYLDB2ConnectionStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYLZDDB2ConnectionStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYLDB2ConnectionString_VB6OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public index() {
            this.Url = global::OCV.Properties.Settings.Default.OCV_YL_WebService_index;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetYLDB2ConnectionStringCompletedEventHandler GetYLDB2ConnectionStringCompleted;
        
        /// <remarks/>
        public event GetYLZDDB2ConnectionStringCompletedEventHandler GetYLZDDB2ConnectionStringCompleted;
        
        /// <remarks/>
        public event GetYLDB2ConnectionString_VB6CompletedEventHandler GetYLDB2ConnectionString_VB6Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://kinte.com/HelloWorld", RequestNamespace="http://kinte.com/", ResponseNamespace="http://kinte.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://kinte.com/GetYLDB2ConnectionString", RequestNamespace="http://kinte.com/", ResponseNamespace="http://kinte.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetYLDB2ConnectionString() {
            object[] results = this.Invoke("GetYLDB2ConnectionString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetYLDB2ConnectionStringAsync() {
            this.GetYLDB2ConnectionStringAsync(null);
        }
        
        /// <remarks/>
        public void GetYLDB2ConnectionStringAsync(object userState) {
            if ((this.GetYLDB2ConnectionStringOperationCompleted == null)) {
                this.GetYLDB2ConnectionStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYLDB2ConnectionStringOperationCompleted);
            }
            this.InvokeAsync("GetYLDB2ConnectionString", new object[0], this.GetYLDB2ConnectionStringOperationCompleted, userState);
        }
        
        private void OnGetYLDB2ConnectionStringOperationCompleted(object arg) {
            if ((this.GetYLDB2ConnectionStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYLDB2ConnectionStringCompleted(this, new GetYLDB2ConnectionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://kinte.com/GetYLZDDB2ConnectionString", RequestNamespace="http://kinte.com/", ResponseNamespace="http://kinte.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetYLZDDB2ConnectionString() {
            object[] results = this.Invoke("GetYLZDDB2ConnectionString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetYLZDDB2ConnectionStringAsync() {
            this.GetYLZDDB2ConnectionStringAsync(null);
        }
        
        /// <remarks/>
        public void GetYLZDDB2ConnectionStringAsync(object userState) {
            if ((this.GetYLZDDB2ConnectionStringOperationCompleted == null)) {
                this.GetYLZDDB2ConnectionStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYLZDDB2ConnectionStringOperationCompleted);
            }
            this.InvokeAsync("GetYLZDDB2ConnectionString", new object[0], this.GetYLZDDB2ConnectionStringOperationCompleted, userState);
        }
        
        private void OnGetYLZDDB2ConnectionStringOperationCompleted(object arg) {
            if ((this.GetYLZDDB2ConnectionStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYLZDDB2ConnectionStringCompleted(this, new GetYLZDDB2ConnectionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://kinte.com/GetYLDB2ConnectionString_VB6", RequestNamespace="http://kinte.com/", ResponseNamespace="http://kinte.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetYLDB2ConnectionString_VB6() {
            object[] results = this.Invoke("GetYLDB2ConnectionString_VB6", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetYLDB2ConnectionString_VB6Async() {
            this.GetYLDB2ConnectionString_VB6Async(null);
        }
        
        /// <remarks/>
        public void GetYLDB2ConnectionString_VB6Async(object userState) {
            if ((this.GetYLDB2ConnectionString_VB6OperationCompleted == null)) {
                this.GetYLDB2ConnectionString_VB6OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYLDB2ConnectionString_VB6OperationCompleted);
            }
            this.InvokeAsync("GetYLDB2ConnectionString_VB6", new object[0], this.GetYLDB2ConnectionString_VB6OperationCompleted, userState);
        }
        
        private void OnGetYLDB2ConnectionString_VB6OperationCompleted(object arg) {
            if ((this.GetYLDB2ConnectionString_VB6Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYLDB2ConnectionString_VB6Completed(this, new GetYLDB2ConnectionString_VB6CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetYLDB2ConnectionStringCompletedEventHandler(object sender, GetYLDB2ConnectionStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYLDB2ConnectionStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYLDB2ConnectionStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetYLZDDB2ConnectionStringCompletedEventHandler(object sender, GetYLZDDB2ConnectionStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYLZDDB2ConnectionStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYLZDDB2ConnectionStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetYLDB2ConnectionString_VB6CompletedEventHandler(object sender, GetYLDB2ConnectionString_VB6CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYLDB2ConnectionString_VB6CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYLDB2ConnectionString_VB6CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591